version: "3.7"
services:
  devenv:
    user: vscode

    build:
      context: .
      dockerfile: Dockerfile
      args:
        #  in your host machine, use "stat -c '%g' docker" to obtain the id for the group named docker
        - DOCKER_GUID=966

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspace:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.config/gh:/home/vscode/.config/gh:cached
      - ~/.kube:/home/vscode/.kube:cached 

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
