SHELL:=/bin/bash
MAKE:=make

.PHONY: simplebot visionbot langbot moderatebot

simplebot:
	@$(MAKE) -C cmd/04.simple-bot all
visionbot:
	@$(MAKE) -C cmd/05.vision-bot all
langbot:
	@$(MAKE) -C cmd/06.lang-bot all
moderatebot:
	@$(MAKE) -C cmd/07.moderate-bot all